//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest.InnaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepositInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DepositInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal DepositField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RateIsoCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Deposit {
            get {
                return this.DepositField;
            }
            set {
                if ((this.DepositField.Equals(value) != true)) {
                    this.DepositField = value;
                    this.RaisePropertyChanged("Deposit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RateIsoCode {
            get {
                return this.RateIsoCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RateIsoCodeField, value) != true)) {
                    this.RateIsoCodeField = value;
                    this.RaisePropertyChanged("RateIsoCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InnaService.BookServiceSoap")]
    public interface BookServiceSoap {
        
        // CODEGEN: Generating message contract since element name CreateDogovorResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateDogovor", ReplyAction="*")]
        ServiceTest.InnaService.CreateDogovorResponse CreateDogovor(ServiceTest.InnaService.CreateDogovorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateDogovor", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.InnaService.CreateDogovorResponse> CreateDogovorAsync(ServiceTest.InnaService.CreateDogovorRequest request);
        
        // CODEGEN: Generating message contract since element name dogovorCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateDogovorPayment", ReplyAction="*")]
        ServiceTest.InnaService.CreateDogovorPaymentResponse CreateDogovorPayment(ServiceTest.InnaService.CreateDogovorPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateDogovorPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.InnaService.CreateDogovorPaymentResponse> CreateDogovorPaymentAsync(ServiceTest.InnaService.CreateDogovorPaymentRequest request);
        
        // CODEGEN: Generating message contract since element name GetDepositAndReceivableResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepositAndReceivable", ReplyAction="*")]
        ServiceTest.InnaService.GetDepositAndReceivableResponse GetDepositAndReceivable(ServiceTest.InnaService.GetDepositAndReceivableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepositAndReceivable", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.InnaService.GetDepositAndReceivableResponse> GetDepositAndReceivableAsync(ServiceTest.InnaService.GetDepositAndReceivableRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDogovorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDogovor", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.InnaService.CreateDogovorRequestBody Body;
        
        public CreateDogovorRequest() {
        }
        
        public CreateDogovorRequest(ServiceTest.InnaService.CreateDogovorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateDogovorRequestBody {
        
        public CreateDogovorRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDogovorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDogovorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.InnaService.CreateDogovorResponseBody Body;
        
        public CreateDogovorResponse() {
        }
        
        public CreateDogovorResponse(ServiceTest.InnaService.CreateDogovorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateDogovorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateDogovorResult;
        
        public CreateDogovorResponseBody() {
        }
        
        public CreateDogovorResponseBody(string CreateDogovorResult) {
            this.CreateDogovorResult = CreateDogovorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDogovorPaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDogovorPayment", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.InnaService.CreateDogovorPaymentRequestBody Body;
        
        public CreateDogovorPaymentRequest() {
        }
        
        public CreateDogovorPaymentRequest(ServiceTest.InnaService.CreateDogovorPaymentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateDogovorPaymentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dogovorCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int paymentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string paymentSys;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal paidSum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string paymentId;
        
        public CreateDogovorPaymentRequestBody() {
        }
        
        public CreateDogovorPaymentRequestBody(string dogovorCode, int paymentType, string paymentSys, decimal paidSum, string paymentId) {
            this.dogovorCode = dogovorCode;
            this.paymentType = paymentType;
            this.paymentSys = paymentSys;
            this.paidSum = paidSum;
            this.paymentId = paymentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDogovorPaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDogovorPaymentResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.InnaService.CreateDogovorPaymentResponseBody Body;
        
        public CreateDogovorPaymentResponse() {
        }
        
        public CreateDogovorPaymentResponse(ServiceTest.InnaService.CreateDogovorPaymentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateDogovorPaymentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateDogovorPaymentResult;
        
        public CreateDogovorPaymentResponseBody() {
        }
        
        public CreateDogovorPaymentResponseBody(string CreateDogovorPaymentResult) {
            this.CreateDogovorPaymentResult = CreateDogovorPaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepositAndReceivableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepositAndReceivable", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.InnaService.GetDepositAndReceivableRequestBody Body;
        
        public GetDepositAndReceivableRequest() {
        }
        
        public GetDepositAndReceivableRequest(ServiceTest.InnaService.GetDepositAndReceivableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDepositAndReceivableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int partnerId;
        
        public GetDepositAndReceivableRequestBody() {
        }
        
        public GetDepositAndReceivableRequestBody(int partnerId) {
            this.partnerId = partnerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepositAndReceivableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepositAndReceivableResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.InnaService.GetDepositAndReceivableResponseBody Body;
        
        public GetDepositAndReceivableResponse() {
        }
        
        public GetDepositAndReceivableResponse(ServiceTest.InnaService.GetDepositAndReceivableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDepositAndReceivableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceTest.InnaService.DepositInfo[] GetDepositAndReceivableResult;
        
        public GetDepositAndReceivableResponseBody() {
        }
        
        public GetDepositAndReceivableResponseBody(ServiceTest.InnaService.DepositInfo[] GetDepositAndReceivableResult) {
            this.GetDepositAndReceivableResult = GetDepositAndReceivableResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookServiceSoapChannel : ServiceTest.InnaService.BookServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServiceSoapClient : System.ServiceModel.ClientBase<ServiceTest.InnaService.BookServiceSoap>, ServiceTest.InnaService.BookServiceSoap {
        
        public BookServiceSoapClient() {
        }
        
        public BookServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.InnaService.CreateDogovorResponse ServiceTest.InnaService.BookServiceSoap.CreateDogovor(ServiceTest.InnaService.CreateDogovorRequest request) {
            return base.Channel.CreateDogovor(request);
        }
        
        public string CreateDogovor() {
            ServiceTest.InnaService.CreateDogovorRequest inValue = new ServiceTest.InnaService.CreateDogovorRequest();
            inValue.Body = new ServiceTest.InnaService.CreateDogovorRequestBody();
            ServiceTest.InnaService.CreateDogovorResponse retVal = ((ServiceTest.InnaService.BookServiceSoap)(this)).CreateDogovor(inValue);
            return retVal.Body.CreateDogovorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.InnaService.CreateDogovorResponse> ServiceTest.InnaService.BookServiceSoap.CreateDogovorAsync(ServiceTest.InnaService.CreateDogovorRequest request) {
            return base.Channel.CreateDogovorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.InnaService.CreateDogovorResponse> CreateDogovorAsync() {
            ServiceTest.InnaService.CreateDogovorRequest inValue = new ServiceTest.InnaService.CreateDogovorRequest();
            inValue.Body = new ServiceTest.InnaService.CreateDogovorRequestBody();
            return ((ServiceTest.InnaService.BookServiceSoap)(this)).CreateDogovorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.InnaService.CreateDogovorPaymentResponse ServiceTest.InnaService.BookServiceSoap.CreateDogovorPayment(ServiceTest.InnaService.CreateDogovorPaymentRequest request) {
            return base.Channel.CreateDogovorPayment(request);
        }
        
        public string CreateDogovorPayment(string dogovorCode, int paymentType, string paymentSys, decimal paidSum, string paymentId) {
            ServiceTest.InnaService.CreateDogovorPaymentRequest inValue = new ServiceTest.InnaService.CreateDogovorPaymentRequest();
            inValue.Body = new ServiceTest.InnaService.CreateDogovorPaymentRequestBody();
            inValue.Body.dogovorCode = dogovorCode;
            inValue.Body.paymentType = paymentType;
            inValue.Body.paymentSys = paymentSys;
            inValue.Body.paidSum = paidSum;
            inValue.Body.paymentId = paymentId;
            ServiceTest.InnaService.CreateDogovorPaymentResponse retVal = ((ServiceTest.InnaService.BookServiceSoap)(this)).CreateDogovorPayment(inValue);
            return retVal.Body.CreateDogovorPaymentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.InnaService.CreateDogovorPaymentResponse> ServiceTest.InnaService.BookServiceSoap.CreateDogovorPaymentAsync(ServiceTest.InnaService.CreateDogovorPaymentRequest request) {
            return base.Channel.CreateDogovorPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.InnaService.CreateDogovorPaymentResponse> CreateDogovorPaymentAsync(string dogovorCode, int paymentType, string paymentSys, decimal paidSum, string paymentId) {
            ServiceTest.InnaService.CreateDogovorPaymentRequest inValue = new ServiceTest.InnaService.CreateDogovorPaymentRequest();
            inValue.Body = new ServiceTest.InnaService.CreateDogovorPaymentRequestBody();
            inValue.Body.dogovorCode = dogovorCode;
            inValue.Body.paymentType = paymentType;
            inValue.Body.paymentSys = paymentSys;
            inValue.Body.paidSum = paidSum;
            inValue.Body.paymentId = paymentId;
            return ((ServiceTest.InnaService.BookServiceSoap)(this)).CreateDogovorPaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.InnaService.GetDepositAndReceivableResponse ServiceTest.InnaService.BookServiceSoap.GetDepositAndReceivable(ServiceTest.InnaService.GetDepositAndReceivableRequest request) {
            return base.Channel.GetDepositAndReceivable(request);
        }
        
        public ServiceTest.InnaService.DepositInfo[] GetDepositAndReceivable(int partnerId) {
            ServiceTest.InnaService.GetDepositAndReceivableRequest inValue = new ServiceTest.InnaService.GetDepositAndReceivableRequest();
            inValue.Body = new ServiceTest.InnaService.GetDepositAndReceivableRequestBody();
            inValue.Body.partnerId = partnerId;
            ServiceTest.InnaService.GetDepositAndReceivableResponse retVal = ((ServiceTest.InnaService.BookServiceSoap)(this)).GetDepositAndReceivable(inValue);
            return retVal.Body.GetDepositAndReceivableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.InnaService.GetDepositAndReceivableResponse> ServiceTest.InnaService.BookServiceSoap.GetDepositAndReceivableAsync(ServiceTest.InnaService.GetDepositAndReceivableRequest request) {
            return base.Channel.GetDepositAndReceivableAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.InnaService.GetDepositAndReceivableResponse> GetDepositAndReceivableAsync(int partnerId) {
            ServiceTest.InnaService.GetDepositAndReceivableRequest inValue = new ServiceTest.InnaService.GetDepositAndReceivableRequest();
            inValue.Body = new ServiceTest.InnaService.GetDepositAndReceivableRequestBody();
            inValue.Body.partnerId = partnerId;
            return ((ServiceTest.InnaService.BookServiceSoap)(this)).GetDepositAndReceivableAsync(inValue);
        }
    }
}
